table 'Measures Table'
	lineageTag: 7a49a266-5e6c-4ca6-9e25-96bfeb443e40

	measure 'Work Hours weekly' = MAX(WeeklyHours[WeeklyHours])
		lineageTag: 9e88f2c0-130f-4b71-a982-84bd3301cb09

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TimeSpent =
			CALCULATE(
			    COUNT(Pivotted[Time])/4
			)
		formatString: 0.00
		lineageTag: 72362d49-589e-4229-8757-02193ce239c1

	measure 'Excess Accrued' =
			CALCULATE(
			    [TimeSpent] - DISTINCTCOUNT(Pivotted[Week Start - Sort]) * [Work Hours weekly]
			    , FILTER(Pivotted, Pivotted[Parent Activity] <> "lunch")
			)
		lineageTag: 4519addd-bea4-4ece-a857-17d4c97eacf4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Worked time' =
			CALCULATE(
			    [TimeSpent]
			    , FILTER(Pivotted, Pivotted[Parent Activity] <> "lunch")
			    , FILTER(Pivotted, Pivotted[Parent Activity] <> "leave")
			)
		lineageTag: 0e460c1c-e149-4c3d-9858-f7d5fe83ebf7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Measures Table' = m
		mode: import
		queryGroup: '00 utilities'
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

