Active Accounts = CALCULATE(
    COUNTx(
        FILTER(
            'Accounts'
            ,'Accounts'[TimeCreated] <= max(DateDimension[TheDate]) // end max
            && (
                ISBLANK('Accounts'[SuspendedDate]) 
                || 'Accounts'[SuspendedDate] > max(DateDimension[TheDate])
            )
            && not(ISBLANK('Accounts'[firstLogin]))
        )
        , DISTINCTCOUNT('Accounts'[Facilitator_Key])
    )
) // https://community.fabric.microsoft.com/t5/Community-Blog/HR-Analytics-Active-Employee-Hire-and-Termination-trend/ba-p/882970

Suspended Accounts = CALCULATE(
    DISTINCTCOUNT('Accounts'[Facilitator_Key])
    , USERELATIONSHIP('Accounts'[SuspendedDate] ,DateDimension[TheDate])
    , not(ISBLANK('Accounts'[firstLogin]))
) // https://community.fabric.microsoft.com/t5/Community-Blog/HR-Analytics-Active-Employee-Hire-and-Termination-trend/ba-p/882970
// using firstLogin as filter to exclude service accounts

Accounts Active in period = [Active Accounts] + [Suspended Accounts]