Regions covered = CALCULATE(
    CONCATENATEX(
        DISTINCT('Locations'[region])
        , 'Locations'[region]
        , UNICHAR(10)
    ) // end CONCATENATEX
    , NOT(ISBLANK('Locations'[region]))
) // end calculate

// generates a list of all regions where at least one record is associated w/ said region 